"use client";

import React, { useState } from 'react';
import { Sparkles, Copy, Download } from 'lucide-react';
import { Textarea, Select, Button, Alert } from '@/components/ui';

export function ContentGenerator() {
  const [prompt, setPrompt] = useState('');
  const [contentType, setContentType] = useState('blog');
  const [generatedContent, setGeneratedContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    setIsGenerating(true);
    // Simulate API call
    setTimeout(() => {
      setGeneratedContent(`Generated ${contentType} content based on: "${prompt}"\n\nThis is a sample AI-generated content. In production, this would be generated by an AI service like OpenAI.`);
      setIsGenerating(false);
    }, 2000);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">AI Content Generator</h1>
        <p className="text-gray-600 mt-1">Create content with AI assistance</p>
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* Input */}
        <div className="space-y-4">
          <div className="bg-white rounded-xl border border-gray-200 p-6">
            <h3 className="font-bold text-gray-900 mb-4">Content Settings</h3>
            
            <Select
              label="Content Type"
              value={contentType}
              onChange={(e) => setContentType(e.target.value)}
              options={[
                { value: 'blog', label: 'Blog Post' },
                { value: 'email', label: 'Email' },
                { value: 'social', label: 'Social Media' },
                { value: 'ad', label: 'Advertisement' },
              ]}
            />
            
            <div className="mt-4">
              <Textarea
                label="Describe what you want to create"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="E.g., Write a blog post about the benefits of cloud computing..."
                rows={6}
              />
            </div>
            
            <button
              onClick={handleGenerate}
              disabled={!prompt || isGenerating}
              className="w-full mt-4 flex items-center justify-center gap-2 px-6 py-3 rounded-full text-white font-semibold shadow-lg hover:shadow-xl transition-all disabled:opacity-50"
              style={{ backgroundColor: '#fc6813' }}
            >
              <Sparkles className="w-5 h-5" />
              {isGenerating ? 'Generating...' : 'Generate Content'}
            </button>
          </div>
        </div>

        {/* Output */}
        <div className="space-y-4">
          <div className="bg-white rounded-xl border border-gray-200 p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-bold text-gray-900">Generated Content</h3>
              {generatedContent && (
                <div className="flex gap-2">
                  <button className="p-2 rounded-lg hover:bg-gray-100 transition-colors">
                    <Copy className="w-4 h-4 text-gray-600" />
                  </button>
                  <button className="p-2 rounded-lg hover:bg-gray-100 transition-colors">
                    <Download className="w-4 h-4 text-gray-600" />
                  </button>
                </div>
              )}
            </div>
            
            {generatedContent ? (
              <div className="prose max-w-none">
                <p className="text-gray-700 whitespace-pre-wrap">{generatedContent}</p>
              </div>
            ) : (
              <div className="text-center py-12 text-gray-400">
                <Sparkles className="w-12 h-12 mx-auto mb-4" />
                <p>Your generated content will appear here</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
